# Generated by Django 4.2.17 on 2024-12-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='breeds',
            new_name='breed',
        ),
    ]
