# Generated by Django 4.2.17 on 2024-12-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_rename_breeds_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
