# Generated by Django 4.2.17 on 2025-01-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'permissions': [('can_add_pet', 'can add pet')]},
        ),
    ]
