# Generated by Django 4.2.17 on 2025-01-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
