# Generated by Django 4.2.17 on 2025-01-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_alter_pet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='first_time_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breed',
            name='good_with_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breed',
            name='low_shedding',
            field=models.BooleanField(default=False),
        ),
    ]
