# Generated by Django 4.2.17 on 2025-01-06 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpage', '0013_breed_activity_level_breed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
