# Generated by Django 4.2.17 on 2025-01-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_alter_adoption_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adoption',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoption',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adoption',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
