# Generated by Django 5.1.4 on 2025-01-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0016_breed_guard_dog_breed_athletic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
