# Generated by Django 4.2.17 on 2025-01-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0020_adoption_approval_alter_adoption_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
