# Generated by Django 4.2.17 on 2025-02-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0021_alter_adoption_phone_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/image/'),
        ),
    ]
