# Generated by Django 4.2.17 on 2025-02-12 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0022_breed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 15 digits long', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 15 digits long', regex='^\\d{10,15}$')]),
        ),
    ]
