# Generated by Django 4.2.17 on 2025-02-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0023_alter_adoption_phone_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='approval',
            field=models.BooleanField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
