# Generated by Django 4.2.17 on 2025-02-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0024_alter_adoption_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
