# Generated by Django 4.2.17 on 2025-03-27 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0025_alter_adoption_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='adopted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long', regex='^\\d{10}$')]),
        ),
    ]
